// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace ExamenParcialDos
{
	public partial class TweetsCell : UITableViewCell
	{
        public TweetsCell(IntPtr handle) : base(handle)
        {
        }

        public string NumeroMeGusta
        {
            get => lblLiked.Text;
            set => lblLiked.Text = value;
        }

        public string Tweet
        {
            get => lblTweet.Text;
            set => lblTweet.Text = value;
        }

	}
}
