// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DiarioApp
{
	public partial class TableControlController : UITableView
	{
		public TableControlController (IntPtr handle) : base (handle)
		{
		}
	}
}
