// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DiarioApp
{
	public partial class CellController : UITableViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CellController));


        public string Titulo
        {
            get => lblTitulo.Text;
            set => lblTitulo.Text = value;
        }

        public UIImage Mes
        {
            get => imgMes.Image;
            set => imgMes.Image = value;
        }

        public string Descripcion
        {
            get => lblDescripcion.Text;
            set => lblDescripcion.Text = value;
        }

        public UIImage Adjunto
        {
            get => imgAdjunto.Image;
            set => imgAdjunto.Image = value;
        }

        public string Dia
        {
            get => lblDiaM.Text;
            set => lblDiaM.Text = value;
        }

		public CellController (IntPtr handle) : base (handle)
		{
		}

	}
}
